# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd077bdb9-f113-47e1-8692-92e4e8e031ff'
  imageRepository: 'task'
  containerRegistry: 'https://98.66.209.194/'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default
    steps:
    - powershell: |
        (Get-Content -path 'manifests\deployment.yml') -replace 'TAG_PLACEHOLDER', '$(Build.BuildId)' | Set-Content -path 'manifests\deployment.yml'
      displayName: Replace image tag in deployment manifest
            
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Azure subscription 1(7dec5829-bdf3-4069-86ff-2358b047427d)'
        azureResourceGroup: 'atos-RG'
        kubernetesCluster: 'atos-aks'
        namespace: 'staging'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Container Registry'
        dockerRegistryEndpoint: 'dockerRepo'
        #secretName: 'nexussecret'
        forceUpdate: false
        checkLatest: true