database=postgres
spring.datasource.url=postgres-postgresql
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
