apiVersion : apps/v1
kind: Deployment
metadata:
  name: springpetclinic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic 
    spec:
      containers:
        - name: springpetclinic 
          image: atosacr22.azurecr.io/springpetclinic
          ports:
          - containerPort: 80